import Icons from "#/components/Icons";

export const STATS_STRIP_ITEMS = [
	{
		id: 1,
		val: 1847,
		suf: "+",
		label: "Fermieri activi",
		sub: "din 32 de județe",
	},
	{
		id: 2,
		val: 142000,
		suf: "",
		label: "Bovine în evidență",
		sub: "identificate prin crotal",
	},
	{
		id: 3,
		val: 98.7,
		suf: "%",
		label: "Raportări acceptate",
		sub: "la ANSVSA din prima",
	},
	{
		id: 4,
		val: 47,
		suf: "h",
		label: "Timp economisit",
		sub: "pe lună, în medie",
	},
];

export const FEATURE_ITEMS: FeatureItem[] = [
	{
		label: "01 · Identificare",
		title: "Scanează crotalul. Gata.",
		body: "Camera telefonului citește codul RO oficial în 800 ms. Animalul e recunoscut instant — rasă, vârstă, istoric, tratamente. Funcționează offline, în grajd, la stână sau pe pășune.",
		icon: Icons.Scan,
		color: "#8DBF91",
		demo: "scan",
	},
	{
		label: "02 · Sănătatea cirezii",
		title: "Fiecare vacă, sub observație.",
		body: "Senzori opționali pe colier monitorizează temperatura, pașii și timpul de rumegat al fiecărui animal. Algoritmul detectează mastita, febra sau călduri cu 36h înainte să fie vizibile cu ochiul — înainte să pierzi producție sau un vițel.",
		icon: Icons.Heart,
		color: "#E86B5A",
		demo: "vitals",
	},
	{
		label: "03 · Reproducție",
		title: "Calendarul care nu uită nimic.",
		body: "Monte, însămânțări, diagnostice de gestație, fătări — totul înregistrat și corelat. Primești notificare cu 21 de zile înainte de fiecare eveniment important.",
		icon: Icons.Calendar,
		color: "#F4B840",
		demo: "calendar",
	},
	{
		label: "04 · Lapte",
		title: "Producție per animal, zilnic.",
		body: "Integrare cu sistemele de muls sau introducere manuală în 4 secunde. Tendințe, grafice, alerte când producția scade cu peste 12%.",
		icon: Icons.Milk,
		color: "#5BB8D4",
		demo: "milk",
	},
	{
		label: "05 · Conformitate",
		title: "Rapoarte ANSVSA cu un clic.",
		body: "Mișcări, tratamente, nașteri, decese — formularele se completează singure din datele din aplicație. Export PDF sau trimitere directă către ANSVSA și APIA.",
		icon: Icons.Shield,
		color: "#8DBF91",
		demo: "report",
	},
	{
		label: "06 · Parcele",
		title: "Pășune, rotație, GPS.",
		body: "Desenezi parcelele pe hartă, setezi rotația, urmărești unde e turma în timp real. Integrare cu blocurile fizice APIA pentru subvenții.",
		icon: Icons.Location,
		color: "#FAD070",
		demo: "map",
	},
];

export const ANIMALS_DUMMY_DATA: Animal[] = [
	{
		id: "RO-2487-M-0941",
		nume: "Floarea",
		rasa: "Bălțată Românească",
		varsta: "4a 2l",
		status: "lactatie",
		parcela: "Pășunea Nord P1",
		lapte: "28.4 L",
		greutate: "612",
		ultimulTratament: "Acum 42 zile",
		last: "14:27",
		timeline: [
			{
				date: "14 Mai",
				time: "14:27",
				event: "Scanat la intrare pășune",
				icon: Icons.Scan,
				color: "#8DBF91",
			},
			{
				date: "12 Mai",
				time: "09:14",
				event: "Muls dimineață · 14.2 L",
				icon: Icons.Milk,
				color: "#5BB8D4",
			},
			{
				date: "02 Apr",
				time: "11:00",
				event: "Vaccin antifebre aftoase · Dr. Pop",
				icon: Icons.Pill,
				color: "#F4B840",
			},
			{
				date: "18 Mar",
				time: "—",
				event: "Mutare P3 → P2 · Pășunea de Sud",
				icon: Icons.Location,
				color: "#6A9B6E",
			},
		],
	},
	{
		id: "RO-2487-M-0883",
		nume: "Brândușa",
		rasa: "Holstein Friză",
		varsta: "5a 8l",
		status: "gestant",
		parcela: "Pășunea Sud P2",
		lapte: "—",
		greutate: "658",
		ultimulTratament: "Acum 12 zile",
		last: "13:55",
		timeline: [
			{
				date: "13 Mai",
				time: "13:55",
				event: "Călduri detectate · senzor",
				icon: Icons.Heart,
				color: "#F4B840",
			},
			{
				date: "10 Mai",
				time: "08:30",
				event: "Control gestație · Dr. Pop",
				icon: Icons.Pill,
				color: "#8DBF91",
			},
			{
				date: "01 Mai",
				time: "—",
				event: "Mutare P2 · protocol gestație",
				icon: Icons.Location,
				color: "#6A9B6E",
			},
			{
				date: "20 Apr",
				time: "10:00",
				event: "Ecografie · zi 165",
				icon: Icons.Scan,
				color: "#5BB8D4",
			},
		],
	},
	{
		id: "RO-2487-M-0756",
		nume: "Ghiocel",
		rasa: "Simmental",
		varsta: "3a 1l",
		status: "bolnav",
		parcela: "Izolator A-3",
		lapte: "—",
		greutate: "598",
		ultimulTratament: "Acum 2 zile",
		last: "10:12",
		timeline: [
			{
				date: "14 Mai",
				time: "10:12",
				event: "Temperatură 39.8°C · izolat",
				icon: Icons.Heart,
				color: "#E86B5A",
			},
			{
				date: "13 Mai",
				time: "16:00",
				event: "Tratament antibiotic · Dr. Pop",
				icon: Icons.Pill,
				color: "#F4B840",
			},
			{
				date: "12 Mai",
				time: "08:45",
				event: "Primele simptome raportate",
				icon: Icons.Bell,
				color: "#E86B5A",
			},
			{
				date: "03 Apr",
				time: "11:00",
				event: "Vaccin antifebre aftoase",
				icon: Icons.Pill,
				color: "#8DBF91",
			},
		],
	},
	{
		id: "RO-2487-M-1204",
		nume: "Dafina",
		rasa: "Bălțată Românească",
		varsta: "6a 4l",
		status: "lactatie",
		parcela: "Pășunea Nord P1",
		lapte: "19.8 L",
		greutate: "634",
		ultimulTratament: "Acum 67 zile",
		last: "Ieri",
		timeline: [
			{
				date: "13 Mai",
				time: "09:00",
				event: "Muls · 19.8 L (–18% vs medie)",
				icon: Icons.Milk,
				color: "#5BB8D4",
			},
			{
				date: "11 Mai",
				time: "09:15",
				event: "Muls · 21.3 L",
				icon: Icons.Milk,
				color: "#5BB8D4",
			},
			{
				date: "08 Mar",
				time: "11:00",
				event: "Vaccin antifebre aftoase",
				icon: Icons.Pill,
				color: "#F4B840",
			},
			{
				date: "14 Feb",
				time: "—",
				event: "Mutare P4 → P1",
				icon: Icons.Location,
				color: "#6A9B6E",
			},
		],
	},
	{
		id: "RO-2487-M-1047",
		nume: "Margareta",
		rasa: "Holstein Friză",
		varsta: "2a 9l",
		status: "sanatos",
		parcela: "Pășunea Est P3",
		lapte: "24.1 L",
		greutate: "541",
		ultimulTratament: "Acum 88 zile",
		last: "Ieri",
		timeline: [
			{
				date: "13 Mai",
				time: "08:50",
				event: "Muls dimineață · 24.1 L",
				icon: Icons.Milk,
				color: "#5BB8D4",
			},
			{
				date: "10 Mai",
				time: "14:00",
				event: "Scanat la ieșire pășune",
				icon: Icons.Scan,
				color: "#8DBF91",
			},
			{
				date: "15 Feb",
				time: "10:30",
				event: "Vaccin · Dr. Ionescu",
				icon: Icons.Pill,
				color: "#F4B840",
			},
			{
				date: "02 Ian",
				time: "—",
				event: "Intrare în efectiv · cumpărată",
				icon: Icons.Location,
				color: "#6A9B6E",
			},
		],
	},
];
